from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BlobStoreProtocol(Protocol):
    def put_json(self, value: Any) -> tuple[str, str]: ...
    def get_json(self, ref: str) -> Any: ...


@runtime_checkable
class StateStoreProtocol(Protocol):
    def create_run(self, *, session_id: str | None = None, initial_state: dict[str, Any] | None = None, retry_policy: dict[str, Any] | None = None) -> tuple[str, str]: ...
    def claim_step(self, *, worker_id: str, run_id: str | None = None, lease_seconds: int = 60) -> Any | None: ...
    def heartbeat(self, *, step_id: str, lease_token: str, lease_seconds: int = 60) -> float: ...
    def recover_expired_leases(self) -> int: ...
    def cancel_run(self, *, run_id: str, reason: str) -> int: ...
    def load_state(self, run_id: str) -> tuple[dict[str, Any], int, str]: ...
    def commit_state_patch(self, *, run_id: str, step_id: str, lease_token: str, base_version: int, patch: dict[str, Any], checkpoint_id: str | None = None) -> int: ...
    def append_event(self, *, run_id: str, event_type: str, payload: dict[str, Any], **kwargs: Any) -> tuple[str, int]: ...
    def create_artifact(self, *, run_id: str, step_id: str | None, name: str, blob_hash: str, blob_ref: str, metadata: dict[str, Any] | None = None) -> str: ...


@runtime_checkable
class ToolExecutorProtocol(Protocol):
    async def call(self, tool_name: str, args: dict[str, Any]) -> Any: ...


@runtime_checkable
class ModelProviderProtocol(Protocol):
    async def call_model(self, request: dict[str, Any]) -> dict[str, Any]: ...
